name: "Heroku Run"
description: "Run a command in a dyno."
branding:
  icon: "terminal"
  color: "purple"
inputs:
  heroku_api_key:
    description: "This will be used for authentication. You can find it in your heroku homepage account settings."
    required: true
  heroku_email:
    description: "Email that you use with heroku."
    required: true
  heroku_app_name:
    description: "The name of the app to run the command in."
    required: true
  command:
    description: "Command to run."
    required: true
outputs:
  status:
    description: "The Success/Failure of the action."
runs:
  using: "node12"
  main: "index.js"
